### ISSUE TITLE
How to connect response to a specific connection.

### ISSUE THREAD

**Issue by michael-grunder** [benashford/redis-async-rs#45]
I hope it's alright to post this here, since this is really not a bug in the library.

I'm putting together a command-line utility to monitor any number of Redis instances asynchronously.  So, essentially:

```Rust
use futures::stream::SelectAll;
use futures::{prelude::*, select, stream::FuturesUnordered};

use redis_async::{
    client::{self, connect::RespConnection},
    resp::RespValue,
    resp_array,
};
use std::{convert::TryInto, error::Error};

async fn get_connection(port: u16) -> Result<RespConnection, std::io::Error> {
    let addr = format!("127.0.0.1:{}", port).parse().unwrap();
    client::connect(&addr).await
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let args = std::env::args().skip(1).collect::<Vec<_>>();

    let mut connections = SelectAll::new();

    for arg in &args {
        let mut con = get_connection(arg.parse().unwrap()).await?;
        con.send(resp_array!["MONITOR"]).await?;
        let con = con.skip(1);
        connections.push(con);
    }

    while let Some(v) = connections.next().await {
        println!("{:?}", v);
    }

    Ok(())
}
```

This works well, but I can't for the life of me figure out how I would go about determining _which_ stream produced a given reply.   It produces `RespValues` but there isn't any context about the stream that produced it (as far as I can tell).

How would you suggest going about this?

Thanks again for the library!

**Comment by michael-grunder** [comment]
In case anyone lands here with the same question, you can use [StreamExt::map](https://docs.rs/futures/0.3.1/futures/stream/trait.StreamExt.html#method.map) to add context.

```Rust
connections.push(con.map(|item| (item, context));
```

**Comment by benashford** [comment]
Cool, you found the answer before I had a chance to response. But I would have recommended the same thing anyway 👍
