### ISSUE TITLE
RespValue Bulk String to String or Integer

### ISSUE THREAD

**Issue by eribol** [benashford/redis-async-rs#46]
I get data with lrange which this data is array. But actualy its string but getting bulkstring from redis. I want to change it to string but i did not see an example for it.

```rust
let one = redis.send(Command(resp_array!["LRANGE", "generates"].append(vec!["0".to_string(),"-1".to_string()])));

        match one.await{
            Ok(res)=>{
                match res{
                    Ok(RespValue::Array(data))=>{
                        let data: Vec<i64> = data[1].into();
                        //let sparkle_heart = std::str::from_utf8(data.into()).unwrap();
                        println!("{:?}", data);
                        Ok(HttpResponse::Ok().content_type("application/json").json("Sorgu tamamlandı"))
                    },
                    _ =>{
                        Ok(HttpResponse::Ok().content_type("application/json").json("Sorgu tamamlandı"))
                    }
                }


            },
            Err(_e)=>{
                Ok(HttpResponse::InternalServerError().json("Sunucu hatası"))
            }
```

**Comment by benashford** [comment]
The library will use type inference to convert the result from Redis into the required type (with the restriction that it has to match the Redis data, obviously, otherwise it will cause an error when parsing the result), as long as that type implements the `FromResp` trait.

So in this case you have a couple of options. You can do:

```rust
let one = redis.send(the_redis_command);
let result: Result<Vec<String>, _> = one.await?;
```

The only downside to this is if `LRANGE` returns an empty set it will cause a runtime error. If you want to handle the empty set to, you'd need:

```rust
let one = redis.send(the_redis_command);
let result: Result<Option<Vec<String>>, _> = one.await?;
```

**Comment by eribol** [comment]
Thank you for your quick answer. I tried your advice;
`let one = redis.send(Command(resp_array!["LRANGE", "generates"].append(vec!["0".to_string(),"-1".to_string()])));
        let result: Result<Option<Vec<u8>>, _> = one.await?;
        match result{
            Ok(res)=>{
                match res{
                    Some(data)=>{
                        Ok(HttpResponse::Ok().content_type("application/json").json("Ok"))
                    },
                    None =>{
                        Ok(HttpResponse::Ok().content_type("application/json").json("Ok"))
                    }
                }


            },
            Err(_e)=>{
                Ok(HttpResponse::InternalServerError().json("Sunucu hatası"))
            }`
and compiler says for one.await?;

> expected enum `std::option::Option`, found enum `redis_async::resp::RespValue`

**Comment by benashford** [comment]
I think I missed something in your first comment. I thought that you were using this library directly, but judging by context it looks like you're using this library indirectly via `actix-redis`?

If this is true then ignore my previous comment as it doesn't apply to that library.

If you have a `RespValue` and you want to convert it into a specific type, you can do something like the following, assuming you have a `Result<RespValue, RedisError>` (e.g. the fourth line of your original example).

```rust
    let res: Result<Vec<String>, _> = res.and_then(FromResp::from_resp);
```

this would also work to handle the empty set

```rust
    let res: Result<Option<Vec<String>>, _> = res.and_then(FromResp::from_resp);
```

Essentially we're using this trait: https://docs.rs/redis-async/0.6.1/redis_async/resp/trait.FromResp.html#method.from_resp to parse the `RespValue` into the desired specific type.

**Comment by eribol** [comment]
Yes i am using actix-redis and this time it gives another error because of it.

> expected enum `redis_async::error::Error`, found enum `actix_redis::Error`
Sorry if this is a silly question. I am not expert, i looked at FromResp but i did not found a solution for my question. 

Thank you for your answers.

**Comment by benashford** [comment]
Actix Redis is new to me too, this is a learning experience for both of us 😁 

Taking a look at the docs it seems there are two error types, one is re-exported from this library and a second one which includes other options for other eventualities. This means the the simple `and_then` doesn't work.

But all we need to do to fix it is to convert that error.

So now we know that the result of the future returned by `send` is: `Result<RespValue, actix_redis::Error>` we can convert that into `Result<Vec<String>, actix_redis::Error>` with:

```rust
let res: Result<Vec<String>, _> = res.and_then(|value| FromResp::from_resp(value).map_err(actix_redis::Error::Redis));
```

This can probably be simplified to:

```rust
let res = res.and_then(|value| Ok::<Vec<String>, _>(FromResp::from_resp(value)?));
```

It may be easier to handle this the long-hand way. It might fit in to the wider code better than the one-liner:

```rust
let res: Result<Vec<String>, _> = match res {
    Ok(resp_value) => match FromResp::from_resp(resp_value) {
        Ok(parsed_value) => Ok(parsed_value),
        Err(resp_error) => Err(actix_redis::Error::Redis(resp_error))
    }
    Err(actix_error) => Err(actix_error)
};
```
Or a fourth version as a compromise:

```rust
let res = match res {
    Ok(resp_value) => Ok::<Vec<String>, _>(FromResp::from_resp(resp_value)?),
    Err(actix_error) => Err(actix_error)
};
```

The more I think about it the more ways there are of going about it 🤔 but essentially all four of those examples should work.

**Comment by eribol** [comment]
Thank you for your long and clear answer. It worked very well.
