### ISSUE TITLE
pubsub failed on MacOs

### ISSUE THREAD

**Issue by linfeng-crypto** [benashford/redis-async-rs#47]
`cargo run --example pubsub` failed with error:

```
thread 'main' panicked at 'Cannot subscribe to topic: Internal("Subscription failed, try again later...")', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by benashford** [comment]
Thanks for the report.

Unfortunately I cannot reproduce the problem. Running on latest Mac OS with Redis 5.0.7 the examples work as expected.

That particular error message would be seen if the Redis server had disappeared and the client was trying to re-connect. But that's unlikely in the case of this example as it only tries to connect once, and if the server isn't running when the initial connection happens you would see a Connection Refused message instead.

Could you specify which Redis version you're running against, e.g. the output of `redid-server --version`

Thanks!

**Comment by linfeng-crypto** [comment]
sorry, I think the host proxy caused the problem(i'm using the [proxifier](https://www.proxifier.com/download/)). All the tcp connection proxied to a `localhost:port`. After i closed the proxifier(Or set the proxifier rule), it works fine.
