### ISSUE TITLE
Make Tokio 1.0 the default?

### ISSUE THREAD

**Issue by davidpdrsn** [benashford/redis-async-rs#66]
Hey! What do you think about making the tokio 1.0 feature the default? Currently 0.3 is the default it seems.

**Comment by benashford** [comment]
Hello,

Yes, I intend on making Tokio 1.0 the default in the next release. And that is currently mostly complete: https://github.com/benashford/redis-async-rs/pull/65 I just need to check the edge-cases before releasing it to try and minimise any surprises.

In the meantime, Tokio 1.0 does work with the current release if you use the `tokio10` feature and disable the default features.

**Comment by davidpdrsn** [comment]
Perfect 👌
